version: "3.2"

services:
  api:
    container_name: agr.stage.intermine.tomcat.server
    image: 100225593120.dkr.ecr.us-east-1.amazonaws.com/agr_intermine_tomcat_env:latest
    logging:
      driver: gelf
      options:
        gelf-address: 'udp://logs.alliancegenome.org:12201'
    ports:
      - "8080:8080"
    networks:
      - intermine
    env_file:
      - .env

networks:
  # The presence of these objects is sufficient to define them
  intermine:
